server:
  port: 9000

logging:
  level:
    root: debug
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
#    org.springframework.boot.autoconfigure: DEBUG