#variables:
#  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#
#before_script:
#  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build


build oauth2-server dev:
  image: registry.yunmotec.com:1443/gradle:7.3.3-jdk11
  tags:
    - java
  stage: build
  script:
    - gradle jib -Djib.to.image=registry.yunmotec.com:1443/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID -Djib.disableUpdateChecks=true -Djib.allowInsecureRegistries=true
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - build
      - .gradle
  only:
    - kexing-dev

build oauth2-server qa:
  image: registry.yunmotec.com:1443/gradle:jdk11
  tags:
    - java
  stage: build
  script:
    - gradle jib -Djib.to.image=registry.yunmotec.com:1443/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID -Djib.disableUpdateChecks=true -Djib.allowInsecureRegistries=true
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - build
      - .gradle
  only:
    - kexing-qa

build oauth2-server prod:
  image: registry.yunmotec.com:1443/gradle:jdk11
  tags:
    - java
  stage: build
  script:
    - gradle jib -Djib.to.auth.username="泉信技术" -Djib.to.auth.password="mBB@vY@n5xQmXmh" -Djib.to.image=registry.cn-beijing.aliyuncs.com/quanxinbim/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME.$CI_PIPELINE_IID
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - build
      - .gradle
  except:
    - develop
    - /^release.*$/
    - /^feature.*$/
  only:
    - tags
