spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.234.34.255:3306/dcs_management?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: dcs_management
    password: mlq9u9k3f0
