server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kexing_management
    username: root
    password: shuju

logging:
  level:
    org:
      springframework:
        security: TRACE
